### ISSUE TITLE
Notification Preferences

### ISSUE THREAD

**Issue by devagrawal09** [TheDynamics/app#175]
Setup notification preferences

**Comment by Hanif-adedotun** [comment]
@devagrawal09 can you give more details on what this about, I want to work on it

**Comment by devagrawal09** [comment]
It's kinda like this page - https://github.com/settings/notifications
Where you can choose what stuff you want to be notified for. For now I think we will just have Email notifications enabled/disable, which also comes from the signup form. This preference will be used to send members certain email notifications along with regular notifications.
You can clarify more details with @D'phenomenal on exactly what notification preferences we would have available. We will add a lot more preferences in the future I believe, right now let's just go for enable/disable email notifications.
Probably a good idea to finish #176 before this one.

**Comment by Hanif-adedotun** [comment]
Okay, I would work on #176 , then this. You can assign both to me
